apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-prod
  annotations:
    policies.kyverno.io/title: Verify Image
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.7.0
spec:
  validationFailureAction: Audit
  background: false
  rules:
    - name: verify-image
      match:
        any:
        - resources:
            kinds:
            - Pod
      exclude:
        any:
        - resources:
            namespaces:
            - prod
      verifyImages:
      - imageReferences:
        - "docker.io/gmontalvoy/hello:*"
        mutateDigest: true
        attestors:
        - entries:
          - keys:
              publicKeys: |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/IjWWdh7Jd6p72Y/1D+TmVGjIp20
                cukXhWknErGhBIwnM5p9wc69S8+/bETXbgUfU7Y9N5grQo9x/u+qZDlHoA==
                -----END PUBLIC KEY-----
